services:
  nginx:
    volumes:
      - ./docker/nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      # No 443 needed for local
    depends_on:
      - auth-service

  auth-service:
    ports:
      - "8081:8080" # Mapea al puerto 8081 para desarrollo local
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis:6379
